# UTS-2 My Songs for You

Halaman ini ditujukan padanya, seseorang spesial yang belum aku temui. Mungkin sekarang ia sedang sibuk mengejar tenggat waktu tugas? atau bersantai sambil menyeruput secangkir kopi panas? oh! atau jangan-jangan.. ia sedang tersesat akibat peta online yang mengatakan bahwa ia harus ambil belokan kedua di bundaran tadi? hahahah, aku tidak tahu. Tapi aku yakin, tanpa sadar, ia sedang menuju ke arah yang sama denganku

## **Puisi: Untukmu yang Akan Datang** {.unnumbered}
Oleh Antania Hanjani Y. P.

> Padanya sosok yang kutahu akan datang  
> Meski kini rupamu masih menjadi bayang  
> Aku tak tahu lirik apa yang kau senandungkan saat senja  
> Atau melodi apa yang membuatmu bahagia  
> 
> Radarku masih hening  
> Jejakmu belum terdeteksi di manapun kau berada  
> Maka biarlah kujalani episode ini seorang diri  
> Merapikan segalanya sebelum kau datang menghampiri  
> 
> Hingga saat semesta lelah menyimpanmu dariku  
> Dan jiwaku berhasil menemukan jiwamu  
> Bukan lagi sebuah pencarian, tapi sebuah pertemuan  
> 
> Ketika saat itu tiba,  
> Hidup yang kujalani dalam sunyi ini,  
> Akan menjadi simfoni yang indah saat bersamamu nanti  


## Lagu: Different Lives {.unnumbered}
Oleh Fly by Midnight


Lagu berikut menggambarkan harapan setelah fase pertemuan itu terjadi dan semuanya mulai berubah menjadi lebih baik


{{< video https://youtu.be/_LoTZE2bKbU?si=S8PtDBvuHxram81f>}}, with lyrics


> [Verse 1]  
> Saw myself  
> Two years ago when I was someone else  
> Back then I loved just like a carousel  
> So many faces goin' in and out  
> That's the way it felt  
> 
> [Pre-Chorus]  
> Like a distant sort of conversation of you and I, you and I  
> Feels like I'm runnin' from my reputation every night, every night  
> 
> [Chorus]  
> 'Cause I've lived different lives, different lives  
> Before you ever made me feel alive, feel alive  
> I haven't felt this fucking terrifiеd, terrified  
> Beforе you, you  
> Those were different times, different times  
> I'm not the one I was at twenty-five, drunk and high  
> Those are all the lives I left behind, left behind  
> For you, you  
> 
> [Verse 2]  
> I see it now (See it now)  
> Few years ahead, it's only you around (You around)  
> Hopped off the wave that kept me watered down (Watered > down)  
> And left the old me in a different town  
> Somewhere it can't be found  
> 
> [Pre-Chorus]  
> Like a distant sort of conversation, I try to hide (I > try to hide) from you and I (From you and I)  
> Feels like I'm closer to a revelation every night, > every night  
> 
> [Chorus]  
> 'Cause I've lived different lives, different lives  
> Before you ever made me feel alive, feel alive  
> I haven't felt this fucking terrified, terrified  
> Before you, you  
> Those were different times, different times  
> I'm not the one I was at twenty-five, drunk and high  
> Those are all the lives I left behind, left behind  
> For you, you  
> 
> [Instrumental Break]  
> 
> [Chorus]  
> I've lived different lives, different lives  
> Before you ever made me feel alive, feel alive  
> I haven't felt this fucking terrified, terrified  
> Before you (Before you), before you   
> Those were different times, different times  
> I'm not the one I was at twenty-five, drunk and high  
> Those are all the lives I left behind, left behind  
> For you, you  
>

**Kalau nanti kami benar-benar bertemu,** tolong ingatkan aku bahwa aku pernah menulis ini